### ISSUE TITLE
Decoding is very slow

### ISSUE THREAD

**Issue by hajaulee** [HotaekHan/SSTDNet#13]
I tested your code with image size 512, and is take a lot of time to decode.
```
Elapsed time of pred : 91.725ms
Decoding..
Elapsed time of decode : 114360.36300000001ms
Avg. elapsed time of pred : 153.09623809523805ms
Avg. elapsed time of decode : 65703.0309047619ms
``` 

I learned that NSM function will run slowly in image with many objects. How can i improve its performance.

**Comment by HotaekHan** [comment]
Hi
Thanks for visit my old code :)

Yes, NMS function runs in about O(N^N). The simplest way is that you can reduce the detected box for NMS function via a bigger threshold.
And my code is not optimized also. if you can fix the input size, you don't need to create the anchors for each decode time.
Btw, I will update my old code as soon as possible.

**Comment by hajaulee** [comment]
Thanks for your reply. I tried nms instead of soft nms in your code, and it run faster for me.
