### ISSUE TITLE
SSTD net details problem

### ISSUE THREAD

**Issue by weishuanglong** [HotaekHan/SSTDNet#5]
Hi, HotaekHan, thanks for sharing the code.

I have a question concerning the details of SSTD net, and I'm really looking forward to see you reply:)

(1) In the deconvolution part, I see that you use groups=64 to upsample. But generally groups=1 might be more reasonale, so I guess it's for saving computational complexity? Or is there any other reasons?

(2) The original paper uses deconv3*3, conv1*1 to eastablish attention map. I see that you're using deconv16*16 and two conv3*3 to do it. Does it mean that this implementation is better than that in the original paper?

It's a very nice code and I really appretite your comment!

Thanks

**Comment by HotaekHan** [comment]
Hi :)
Thanks for comments for my code!

as you know, I'm not the author for this work.
I re-implemented SSTDNet from author's implementation code(https://github.com/BestSonny/SSTD/blob/master/examples/text/model/deploy.prototxt)
please check out author's code!

(1) Group conv filter is good for sparse representation as my think.
(2) And filter size of deconv layer mentioned in paper is some sample to show i think.

**Comment by weishuanglong** [comment]
thanks for replying!

I see the original caffe implementation, and it realy takes a while...

I found a little difference between the original caffe implementation and yours. 

(1) In the SSTNet, caffe implementation uses a residual block(a little bit different from original residual one, but similar ), and batchnorm included. Your implementation uses vgg-like network in the function "_make_head". 

Other parts are almost the same, so I' wondering if this difference makes improvement on the result!

Thanks for carefully replying!

**Comment by HotaekHan** [comment]
original paper used inception block as i know and me neither.
oh, yes. that part is some different with original implementation. because original paper handle text detection problem. but i reimplemented this work for general object detection.
so, I think the somethings like property of anchors can be different.
I meant, the classifier part can be different with original implementation but feature extraction part is same.

**Comment by weishuanglong** [comment]
Thanks!

Yeah the feature extraction part is the same. I guess the classifier could be different regarding to different problems.
