### ISSUE TITLE
anchor areas

### ISSUE THREAD

**Issue by ran337287** [HotaekHan/SSTDNet#6]
I have a question about anchor_areas， the anchor_areas in encoder.py of your code is [16*16., 32*32., ..., 256*256.], and I want to know the reason you set them.  I think they are correlated with feature maps, but I can't get the explicit relation.

**Comment by HotaekHan** [comment]
Hello :)
Thanks for question.
It's really good question :)
the properties of anchor(size, scale or ratio) are related with the ground truth.
I meant, anchor should be similar with bounding box(ground truth) for learning.
so if you set the anchors, you should find some stastics of bounding box(ratio, scale or size) first.
the size of feature map could affect to how many anchors come from the feature map.

**Comment by ran337287** [comment]
So you mean the sizes of anchors are correlated with bounding box, and the number of anchors are correlated with feature maps.
And another question, does the scales of anchors for each feature map are calculated according to ssd?

**Comment by HotaekHan** [comment]
scales of anchor are also come from some stastics of bounding box.
but you can use some default options in ssd or faster rcnn as you say.
anyway, all of things with anchor are related with bounding boxes.

anchors should be matched with bounding box in origial position.
see the function(_get_anchor_boxes). all anchors have positions in original image coordinate.

**Comment by ran337287** [comment]
Thanks for your reply.
