### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by xsvonjhs** [HotaekHan/SSTDNet#9]
> Traceback (most recent call last):
  File "train.py", line 192, in <module>
    train(epoch)
  File "train.py", line 133, in train
    loss = ((loc_loss + cls_loss) / num_matched_anchors) + mask_loss
RuntimeError: invalid argument 3: divide by zero at /pytorch/torch/lib/THC/generic/THCTensorMathPairwise.cu:88

The error occurs while training the model...how should i solve it?

**Comment by HotaekHan** [comment]
sorry for late :(
it looks there are no matched anchor box. it means that your annotation box is not similar with anchor box. you should change the property of anchor box. checkout 'encoder.py'.
and did you solve your previous problem about type error?

**Comment by xsvonjhs** [comment]
it's okay, thanks for your reply!
I'm not sure which part should i change, would you mind giving more details? 
For the type error I've downgraded my pytorch and it works well, thanks for asking :)

**Comment by HotaekHan** [comment]
@xsvonjhs 
please check from line 16 to line 19 in 'encoder.py'.
and if you don't know about what is anchor box, I recommend google it :)

**Comment by srwpf** [comment]
@HotaekHan Could you please tell us what the annotations should look like? Should we annotate the label like what CTPN did? Which means should we annotate a text line with a couple of tiny boxes with equal width? Or just annotate a text line with a single box?

**Comment by HotaekHan** [comment]
@srwpf it's up to you :) this code is for object detection. it meant if you make ground-truth boxes have equal width for each character, then model try to find character. if you make a box have text line, then model find text line. specifically, machine doesn't know what difference between character and text line. the machine only try to find some object looks like ground truth boxes.

**Comment by srwpf** [comment]
@HotaekHan OK, thank you for your patience.
